-- AlterTable
ALTER TABLE "Cliente" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Pedido" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Producto" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
